name = "SeasonalModel"
uuid = "5e2e89da-0fac-4635-bc9d-229a56016a20"
author = ["Dylan Cormet"]
version = "0.0.0"

[deps]
# coming soon

[compat]
julia = "1.5 - 1.9" # based on BifurkationKit's [compat]
